import { createSlice } from '@reduxjs/toolkit';
/** @typedef {import('../../../types').RecipeSummary} RecipeSummary */

/**
 * Search slice
 * JSDoc is used here to define the state shape as a lightweight way to describe
 * the structure of the object for editor tooling. The state shape describes
 * the properties and their types in the Redux slice state managed by this reducer.
 * 
 * A typedef is a lightweight way to describe the shape of an object for editor tooling.
 * By shape I mean the object's properties and their types. Editor tooling includes
 * VS Code IntelliSense and JSDoc-aware tools.
 * 
 * This slice manages search-related state, including the current query,
 * search results, loading status, and error messages. It provides reducers
 * to update each part of the state.
 * 
 * No extraReducers are used here since there are no async thunks associated
 * with this slice. Extra reducers are typically used to handle actions
 * generated by createAsyncThunk or other slices.
 * 
 * State shape:
 * {
 *   query: string,
 *   results: Array<Object>,
 *   loading: boolean,
 *   error: string|null,
 * }
 */
const searchSlice = createSlice({
  name: 'search',
  initialState: {
    query: '',
    results: [],
    loading: false,
    error: null,
  },
  reducers: {
    setQuery(state, action) {
      state.query = action.payload;
    },
    setResults(state, action) {
      state.results = action.payload || [];
    },
    setLoading(state, action) {
      state.loading = !!action.payload;
    },
    setError(state, action) {
      state.error = action.payload || null;
    },
    clearResults(state) {
      state.results = [];
    }
  }
});

export const { setQuery, setResults, setLoading, setError, clearResults } = searchSlice.actions;
export default searchSlice.reducer;
