/**
 * @description This file contains the authentication logic for the application, including 
 * the configuration of Passport strategies for local and JWT authentication. It also 
 * includes middleware to verify users based on their JWTs.
 * @Strategy LocalStrategy is used for local authentication, which involves verifying a 
 * username and password.
 * @Strategy JWTStrategy is used for JWT authentication, which involves verifying a JSON 
 * Web Token.
 * @model The User model is used to handle user authentication and session 
 * management.
 * @Strategy ExtractJwt is used to extract the JWT from the request headers.
 * @note The secret key used to sign the JWT is stored in the config.js file and should be kept secure. 
 * In a production environment, it is recommended to use environment variables or a secure vault for 
 * sensitive information.
 * @note The JavaScript Web Token (JWT) is extracted from the Authorization header as a Bearer token. 
 * This is the easiest way to send the JWT in a request. A Bearer token is a security token that is 
 * generated by the server and sent to the client. The client then includes this token in the 
 * Authorization header of subsequent requests to access protected resources.
*/
const passport = require('passport');
const LocalStrategy = require('passport-local').Strategy; 
const User = require('./models/user');
const JwtStrategy = require('passport-jwt').Strategy; 
const ExtractJwt = require('passport-jwt').ExtractJwt;
/** 
 * @const config Bind constant variable config to the configuration file for secret key 
 *              (config.js) used to sign the JWT (JSON Web Token). 
 * @note *.js file extension is optional.
 * @note ./ in front of config.js because it is in the same directory as authenticate.js 
 * @const jwt - JSON Web Token (JWT) is a compact, URL-safe means of representing claims to be 
 * transferred between two parties.
*/
const jwt = require('jsonwebtoken'); // used to create, sign, and verify tokens
const config = require('./config.js'); 
/**
 * @description Configure Passport to use the local strategy for authentication.
 * The local strategy uses a username and password for authentication.
 * The user is serialized and deserialized to maintain session information.
 */
exports.local = passport.use(new LocalStrategy(User.authenticate()));
passport.serializeUser(User.serializeUser());
passport.deserializeUser(User.deserializeUser());

/**
 * @description Generates a JSON Web Token (JWT) for a given user. 
 * The token is signed using a secret key and has an expiration time of 1 hour.
 * 
 * @param {Object} user - The user object for which the token is generated.
 * @returns {string} JWT token
 */
exports.getToken = user => {    
    return jwt.sign(user, config.secretKey, {expiresIn: 3600});
};
/**
 * @description Options for JWT strategy. The JWT is extracted from the Authorization header 
 * as a Bearer token. This is the easiest way to send the JWT in a request. 
 * The secret key used to sign the JWT is retrieved from the config.js file.
 * @type {Object}
 * @property {function} jwtFromRequest - Function to extract JWT from request.
 * @property {string} secretOrKey - Secret key used to sign the JWT.
 * @property {boolean} ignoreExpiration - Whether to ignore the expiration of the JWT.
 * @property {function} passReqToCallback - Whether to pass the request to the callback.
 * @property {function} callback - The callback function to be executed after extracting the JWT.
 * @property {boolean} session - Whether to use sessions.
 * @method jwtPassport @memberof module:authenticate
 * @param {Object} opts - Options for JWT strategy.
 * @returns {void}
 * @method jwtFromRequest @memberof module:authenticate
 * @param {Object} req - The request object.
 * @returns {string} The JWT extracted from the request.
 * @method secretOrKey @memberof module:authenticate
 * @param {string} secretKey - The secret key used to sign the JWT.
 * @returns {string} The secret key used to sign the JWT.
 * @method ignoreExpiration @memberof module:authenticate
 * @param {boolean} ignoreExpiration - Whether to ignore the expiration of the JWT.
 * @returns {boolean} Whether to ignore the expiration of the JWT.
 * @method passReqToCallback @memberof module:authenticate
 * @param {boolean} passReqToCallback - Whether to pass the request to the callback.
 * @returns {boolean} Whether to pass the request to the callback.
 * @method callback @memberof module:authenticate
 * @param {Object} jwt_payload - The payload of the JWT.
 * @param {function} done - The callback function to be executed after extracting the JWT.
 * @param {Object} user - The user object retrieved from the database.
 * @throws {Error} If there is an error retrieving the user from the database, an error is thrown.
 * @param {boolean} user - Whether the user was found in the database. @memberof module:authenticate
 * @param {function} done - The callback function to be executed after retrieving the user from the database.
 * @returns {void}
 * @method session @memberof module:authenticate
 * @param {boolean} session - Whether to use sessions.
 * @returns {boolean} Whether to use sessions.
 * @method findOne @memberof module:authenticate
*/
const opts = {};
opts.jwtFromRequest = ExtractJwt.fromAuthHeaderAsBearerToken();
opts.secretOrKey = config.secretKey;
// used async function to handle the asynchronous nature of database operations 
// and to use the await keyword for cleaner code. The code would not work with callbacks
// because Mongoose no longer supports the done function being called before the database 
// operation completes, leading to incorrect behavior.
exports.jwtPassport = passport.use(
    new JwtStrategy(
        opts, 
        async (jwt_payload, done) => {
            console.log('JWT payload:', jwt_payload);
            try {
                const user = await User.findOne({_id: jwt_payload._id});
                if (user) {
                    return done(null, user);
                } else {
                    return done(null, false);
                }
            } catch (err) {
                return done(err, false);
            }
        }
    )
);
/**
 * @description Middleware function to verify that the incoming request is from an authenticated user.
 * This function uses the Passport.js library to authenticate the request using the JWT strategy.
 * If the user is authenticated, the request proceeds to the next middleware or route handler.
 * If the user is not authenticated, an error response is sent back to the client.
 * @token JSON Web Token (JWT) is a compact, URL-safe means of representing claims to be transferred between 
 * two parties. A claim is a statement about an entity (typically, the user) and additional metadata.
 * @constant @variable verifyUser is the binding holding the return value of the passport.authenticate function.
 * This makes it available for use in other parts of the application, such as in route handlers where user 
 * authentication is required. 
 * @function passport.authenticate is a middleware function that is used to authenticate requests. It is
 * used here to verify that the incoming request is from an authenticated user. @memberof module:authenticate
 * @param 'jwt' - the strategy to use for authentication. Passport supports various strategies for authentication, 
 * and in this case, the 'jwt' strategy is used to verify the JSON Web Token (JWT) provided in the request. 
 * This strategy is used for stateless authentication and not the local [session-based] strategy.
 * @param @boolean  session - The session option is set to false, indicating that Passport should not create a 
 * session for the user. This is because JWTs are stateless and do not require server-side sessions.
 */
exports.verifyUser = passport.authenticate('jwt', {session: false});